version: 2
 
models:
 - name: google_search_console_keyword_page_report_source
   description: Base model for google search console data
   columns:
     - name: site
       data_tests:
         - not_null
     - name: date
       data_tests:
         - not_null
     - name: device
       data_tests:
         - not_null
     - name: country
       data_tests:
         - not_null
