version: 2

models:
    - name: zengrc_assessment_source
      description: '{{ doc("zengrc_assessments_desc") }}'
      columns: 
        - name: assessment_id
          data_tests:
            - not_null
            - unique

    - name: zengrc_audit_source
      description: '{{ doc("zengrc_audits_desc") }}'
      columns: 
        - name: audit_id
          data_tests:
            - not_null
            - unique

    - name: zengrc_control_source
      description: '{{ doc("zengrc_controls_desc") }}'
      columns: 
        - name: control_id
          data_tests:
            - not_null
            - unique

    - name: zengrc_objective_source
      description: '{{ doc("zengrc_objectives_desc") }}'
      columns: 
        - name: objective_id
          data_tests:
            - not_null
            - unique

    - name: zengrc_issue_source
      description: '{{ doc("zengrc_issues_desc") }}'
      columns: 
        - name: issue_id
          data_tests:
            - not_null
            - unique

    - name: zengrc_request_source
      description: '{{ doc("zengrc_requests_desc") }}'
      columns: 
        - name: request_id
          data_tests:
            - not_null
            - unique

    - name: zengrc_risk_source
      description: '{{ doc("zengrc_risks_desc") }}'
      columns: 
        - name: risk_id
          data_tests:
            - not_null
            - unique
    
    - name: zengrc_vendors_source
      description: '{{ doc("zengrc_vendors_desc") }}'
      columns: 
        - name: vendor_id
          data_tests:
            - not_null
            - unique
    
    - name: zengrc_programs_source
      description: '{{ doc("zengrc_programs_desc") }}'
      columns: 
        - name: program_id
          data_tests:
            - not_null
            - unique