config:
    send_anonymous_usage_stats: False
    use_colors: True
    partial_parse: true

gitlab-snowflake:
  target: prod
  outputs:
    prod_cleanup:
      type: snowflake
      threads: 16
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_LOAD_USER') }}"
      password: "{{ env_var('SNOWFLAKE_LOAD_PASSWORD') }}"
      database: "{{ env_var('SNOWFLAKE_PREP_DATABASE') }}"
      role: "{{ env_var('SNOWFLAKE_LOAD_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_LOAD_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_PREPARATION_SCHEMA') }}"
      client_session_keep_alive: True
    prod:
      type: snowflake
      threads: 16
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      database: "{{ env_var('SNOWFLAKE_PREP_DATABASE') }}"
      role: "{{ env_var('SNOWFLAKE_TRANSFORM_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TRANSFORM_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_PREPARATION_SCHEMA') }}"
      client_session_keep_alive: True
    ci:
      type: snowflake
      threads: 16
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      database: "{{ env_var('SNOWFLAKE_PREP_DATABASE') }}"
      role: "{{ env_var('SNOWFLAKE_TRANSFORM_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TRANSFORM_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_PREPARATION_SCHEMA') }}"
