version: 2

models:
  - name: employee_location_factor_snapshots
    description: This captures changes in location factor for an employee. Starting 2020.03.24 data is captured from bamboohr instead of sheetload.
    columns:
      - name: bamboo_employee_number
        description: bamboo emp id
        data_tests:
          - not_null
      - name: locality
        description: The location associated to the employee.     
      - name: location_factor
        description: The location factor for the given time period
        # data_tests:
        #   - not_null
      - name: valid_from
        description: Marks the start date for a location factor used for an employee
        data_tests:
          - not_null
      - name: valid_to
        description: Marks the end date for a location factor used for an employee
        data_tests:
          - not_null

  - name: sfdc_opportunity_snapshots_source
    description: This captures changes in SFDC Opportunities. 
    columns:
      - name: professional_services_value
        description: Amount on an opportunity that is from Professional Services only
      - name: edu_services_value
        description: Amount on an opportunity that is from Educational Services only
      - name: investment_services_value
        description: Amount on an opportunity that is from Investment Services only
