version: 2

models:
  - name: commonroom_activities_source_pii
    description: '{{ doc("commonroom_activities_source") }}'
  - name: commonroom_community_members_source_pii
    description: '{{ doc("commonroom_community_members_source") }}'
    columns:
      - name: full_name
        data_tests:
          - not_null
  - name: commonroom_organizations_source_pii
    description: '{{ doc("commonroom_organizations_source") }}'
    columns:
      - name: organization_name
        data_tests:
          - not_null
