version: 2

models:
    - name: activity_timeline_pii
      description: '{{ doc("gainsight_activity_timeline") }}'
    - name: advanced_outreach_emails_pii
      description: '{{ doc("gainsight_advanced_outreach_emails") }}'
    - name: advanced_outreach_participants_pii
      description: '{{ doc("gainsight_advanced_outreach_participants") }}'
    - name: companies_and_ebrs_pii
      description: '{{ doc("gainsight_companies_and_ebrs") }}'
    - name: companies_with_success_plan_details_pii
      description: '{{ doc("gainsight_companies_with_success_plan_details") }}'
    - name: email_logs_pii
      description: '{{ doc("gainsight_email_logs") }}'
    - name: nps_survey_response_pii
      description: '{{ doc("gainsight_nps_survey_response") }}'
    - name: opt_out_emails_pii
      description: '{{ doc("gainsight_opt_out_emails") }}'
    - name: user_sfdcgitlabproduction_pii
      description: '{{ doc("gainsight_user_sfdcgitlabproduction") }}'