version: 2

models:
  - name: wk_sales_clari_net_arr_forecast
    description: Forecast table combining the different API sub-payloads together
    columns:
      - name: forecast_id
        data_tests:
          - not_null
      - name: user_full_name
        data_tests:
          - not_null
      - name: user_email
        data_tests:
          - not_null
      - name: crm_user_id
        data_tests:
          - not_null
      - name: sales_team_role
        data_tests:
          - not_null
      - name: parent_role
      - name: fiscal_quarter
        data_tests:
          - not_null
      - name: field_name
        data_tests:
          - not_null
      - name: week_number
        data_tests:
          - not_null
      - name: week_start_date
        data_tests:
          - not_null
      - name: week_end_date
        data_tests:
          - not_null
      - name: field_type
        data_tests:
          - not_null
      - name: forecast_value
      - name: is_updated
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - forecast_id
            - fiscal_quarter
            - week_start_date
            - crm_user_id
            - field_name
  - name: wk_rpt_crm_opportunity_reduced
    description: a table with reduced column list from mart_crm_opportunity that is used for testing entitlement tables for Tableau
    columns:
      - name: dim_crm_opportunity_id
        data_tests:
            - not_null
            - unique
  - name: wk_rpt_crm_account_reduced
    description: a table with reduced column list from mart_crm_account that is used for testing entitlement tables for Tableau
    columns:
      - name: dim_crm_account_id
        data_tests:
            - not_null
            - unique
  - name: wk_prep_crm_account_share_active
    description: an active account share table with reduced column list
    columns:
      - name: account_id
        data_tests:
            - not_null
  - name: wk_prep_crm_opportunity_share_active
    description: an active opportunity share table with reduced column list
    columns:
      - name: opportunity_id
        data_tests:
            - not_null
  - name: wk_crm_account_entitlement
    description: an account entitlment table to be used for row level security in Tableau
    columns:
      - name: account_id
  - name: wk_crm_opportunity_entitlement
    description: an opportunity entitlment table to be used for row level security in Tableau
    columns:
      - name: opportunity_id
  - name: wk_sales_daily_case_automation_test
    description: >
      This is the test model for the PUMP version so we can test changes to the case creation logic.
  - name: wk_sales_gds_account_snapshots
    description: >
      Account snapshots with business logic specific to the Global Digital SMB Sales team
  - name: wk_sales_gds_cases
    description: >
      SFDC cases with Global Digital SMB business logic including activity summary
  - name: wk_sales_gds_fo_buckets
    description: >
      Derives the source of first orders using namespace and trial information
  - name: wk_sales_gds_forecast_consolidated
    description: >
      Monthly forecast model for the Global Digital SMB team
  - name: wk_sales_product_price_quantity
    description: >
      Current price and quantity information based on ARR that can be joined to opportunities
  - name: wk_sales_renewal_arr
    description: >
      Pre- and post-renewal price and quantity information based on ARR to be joined to opportunities
  - name: wk_sales_gds_opportunities
    description : >
      Opportunity data with SMB-specific business logic