version: 2
models:
  - name: adoption_by_group
    description: Adds some additional columns to `adoption_by_group_source` model that are needed for Tableau dashboard
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - group_name
            - aggregated_at
    columns:
      - name: group_name
        data_tests:
          - not_null
      - name: adopted
        data_tests:
          - not_null
      - name: not_adopted
        data_tests:
          - not_null
      - name: total_findings
        data_tests:
          - not_null
      - name: adoption_percentage
        data_tests:
          - not_null
      - name: lower_bound
        data_tests:
          - not_null
      - name: upper_bound
        data_tests:
          - not_null
      - name: adoption_status
        data_tests:
          - not_null
          - accepted_values:
              values: ['at_risk', 'on_track', 'needs_attention']
      - name: minimum_findings
        data_tests:
          - not_null
      - name: is_below_findings_threshold
        data_tests:
          - not_null
      - name: aggregated_at
        data_tests:
          - not_null
  - name: adoption_by_group_latest
    description: Same as `adoption_by_group` but only keeps the most recent batch of data.
    columns:
      - name: group_name
        data_tests:
          - not_null
          - unique
      - name: adopted
        data_tests:
          - not_null
      - name: not_adopted
        data_tests:
          - not_null
      - name: total_findings
        data_tests:
          - not_null
      - name: adoption_percentage
        data_tests:
          - not_null
      - name: lower_bound
        data_tests:
          - not_null
      - name: upper_bound
        data_tests:
          - not_null
      - name: adoption_status
        data_tests:
          - not_null
          - accepted_values:
              values: ['at_risk', 'on_track', 'needs_attention']
      - name: minimum_findings
        data_tests:
          - not_null
      - name: is_below_findings_threshold
        data_tests:
          - not_null
      - name: aggregated_at
        data_tests:
          - not_null
