version: 2

sources:
  - name: just_global_campaigns
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: just_global_campaigns
    loader: Snowflake tasks
    loaded_at_field: uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 7, period: day}
      error_after: {count: 14, period: day}

    tables:
      - name: media_buys
