version: 2
models:
  - name: adoption_by_group_source
    description: Flattens a json object which consists of adoption usage by various gitlab groups
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - group_name
            - aggregated_at
    columns:
      - name: group_name
        data_tests:
          - not_null
      - name: adopted
        data_tests:
          - not_null
      - name: not_adopted
        data_tests:
          - not_null
      - name: lower_bound
        data_tests:
          - not_null
      - name: upper_bound
        data_tests:
          - not_null
      - name: minimum_findings
        data_tests:
          - not_null
      - name: aggregated_at
        data_tests:
          - not_null
