version: 2

sources:
  - name: pajamas_adoption_scanner
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: pajamas_adoption_scanner
    loader: Airflow
    loaded_at_field: uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: adoption_by_group
