version: 2
models:
  - name: kantata_project_details_source
    description: A list of all Professional Services projects and their characteristics stored in Kantata (i.e., Mavenlink)
    columns:
      - name: project_name
        data_tests:
          - not_null
      - name: id
        data_tests:
          - not_null
      - name: client_name
      - name: user_type
      - name: account_name
      - name: opportunity_id
      - name: engagement_manager_name
      - name: gitlab_project_link
      - name: sfdc_ps_description
      - name: invoice_number
      - name: processed_change_order
      - name: status_color
      - name: sponsor_notes
      - name: project_retrospective
      - name: if_no_project_retrospective_why
      - name: project_investment
      - name: sfdc_project_scope
      - name: sfdc_scoping_issue_link
      - name: security_requirement
      - name: project_staffing
      - name: uploaded_at
        data_tests:
          - not_null
  - name: kantata_project_budget_source
    description: A list of all Professional Services projects and related budget details stored in Kantata (i.e., Mavenlink)
    columns:
      - name: project_name
        data_tests:
          - not_null
      - name: id
        data_tests:
          - not_null
      - name: user_type
      - name: budget_used
      - name: over_budget
      - name: current_status_message
      - name: archived
      - name: rate_card
      - name: billing_mode_default
      - name: delivery_method
      - name: opportunity_id
      - name: project_investment
      - name: project_start
      - name: project_due
      - name: project_completed
      - name: project_created
      - name: project_components
      - name: bill_rate
      - name: uploaded_at
        data_tests:
          - not_null
  - name: kantata_revenue_by_user_source
    description: A weekly summary of revenue by delivery resource generated from Kantata (i.e., Mavenlink)
    columns:
      - name: booking_date
      - name: region
      - name: project_name
        data_tests:
          - not_null
      - name: project_components
      - name: category
      - name: project_type
      - name: services
      - name: user_type
      - name: user_role
      - name: user_name
      - name: project_id
        data_tests:
          - not_null
      - name: project_investment
      - name: billing_mode_default
      - name: week_mon_sun
      - name: hours_billed
      - name: fixed_fee_revenue
      - name: t_m_revenue
      - name: revenue
      - name: uploaded_at
        data_tests:
          - not_null
  - name: kantata_weekly_forecast_source
    description: A weekly summary of the "hard" allocated forecast hours generated from Kantata (i.e., Mavenlink)
    columns:
      - name: account_name
      - name: opportunity_id
      - name: opportunity_region
      - name: project_lead
      - name: project_name
        data_tests:
          - not_null
      - name: project_offering
      - name: project_investment
      - name: project_id
        data_tests:
          - not_null
      - name: billing_type
      - name: week_mon_sun
      - name: fixed_fee_education_forecast
      - name: fixed_fee_consulting_forecast
      - name: fixed_fee_other_forecast
      - name: allocations
      - name: forecast
      - name: consulting_rollup
      - name: uploaded_at
        data_tests:
          - not_null
  - name: kantata_remaining_to_forecast_source
    description: A weekly summary of the "hard" allocated forecast hours generated from Kantata (i.e., Mavenlink)
    columns:
      - name: account_name
      - name: opportunity_id
      - name: opportunity_region
      - name: project_lead
      - name: project_name
        data_tests:
          - not_null
      - name: project_offering
      - name: project_investment
      - name: project_id
        data_tests:
          - not_null
      - name: billing_type
      - name: week_mon_sun
      - name: fixed_fee_education_forecast
      - name: fixed_fee_consulting_forecast
      - name: fixed_fee_other_forecast
      - name: allocations
      - name: forecast
      - name: consulting_rollup
      - name: uploaded_at
        data_tests:
          - not_null
