version: 2

sources:
  - name: kantata
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: kantata
    loader: Airflow
    loaded_at_field: uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: nc_project_details_table_including_custom_fields
      - name: nc_project_budget_details
      - name: rev_qbr_details_by_project_user
      - name: forecast_ff_t_m_table_week
      - name: remaining_to_forecast
