version: 2

models:
  - name: dim_subscription_snapshot_model
    description: '{{ doc("dim_subscription_snapshot_model") }}'

  - name: dim_plan
    columns:
      - name: dim_plan_sk
        data_tests:
          - not_null
          - unique
        description: '{{ doc("dim_plan_sk") }}'
      - name: dim_plan_id
        description: '{{ doc("dim_plan_id") }}'
      - name: plan_id_modified
        description: '{{ doc("plan_id_modified") }}'
      - name: plan_name
        description: '{{ doc("plan_name") }}'
      - name: plan_name_modified
        description: '{{ doc("plan_name_modified") }}'
      - name: plan_title
        description: '{{ doc("plan_title") }}'
      - name: is_plan_paid
        description: '{{ doc("is_plan_paid") }}'
