version: 2

sources:
  - name: aws_billing
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: aws_billing
    loader: Airflow

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: dedicated_legacy_0475
      - name: dedicated_dev_3675
      - name: gitlab_marketplace_5127
      - name: itorg_3027
      - name: legacy_gitlab_0347
      - name: services_org_6953
