version: 2

sources:
  - name: hyperproof
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: hyperproof
    loader: Airflow
    
    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: controls
      - name: programs
      - name: roles
      - name: taskstatuses
      - name: users

