version: 2
 
sources:
 - name: e2e_metrics
   database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
   schema: e2e_metrics
   loaded_at_field: uploaded_at
   loader: Snowflake tasks
   description: e2e metrics data [Original Epic](https://gitlab.com/groups/gitlab-data/-/epics/1225)
 
   tables:
     - name: fabrication_stats
     - name: main_test_stats
     - name: all_test_stats