version: 2

models:
    - name: zendesk_ticket_audits
      description: This is the base model for Zendesk ticket audit events.
      columns:
      - name: audit_id
        data_tests:
            - not_null
      - name: ticket_id
        data_tests:
            - not_null
    - name: zendesk_ticket_custom_fields
      description: Dimension / base model of only custom fields available for tickets with extra infromation.
    - name: zendesk_ticket_custom_field_values_clean
      description: This is the ticket custom field values filtered to only necessary, non-sensitive fields.
    - name: zendesk_ticket_custom_field_values_sensitive
      description: This is the fully exploded, sensitive, zendesk ticket custom field values.
      columns:
      - name: ticket_custom_field_id
        data_tests:
          - not_null:
              severity: warn
    - name: zendesk_ticket_metrics
      description: This is the base model for Zendesk ticket metrics.
      columns:
      - name: ticket_id
        data_tests:
            - unique
            - not_null
      - name: ticket_metrics_id
        data_tests:
            - unique
            - not_null                  
    - name: zendesk_ticket_tags
      columns:
        - name: ticket_id
          data_tests:
            - not_null
    - name: zendesk_users
      description: This is the base model for Zendesk Users
      columns:
      - name: user_id
        data_tests:
            - not_null
