version: 2

sources:
  - name: rally_initial_export
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: rally_initial_export
    loader: Airflow
    loaded_at_field: updated_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: rally_initial_export_optouts
