version: 2

models:
  - name: sirt_alertapp_data_source
    description: Data on each media buy and corresponding performance
    columns:
      - name: alertid
        data_tests:
          - not_null
      - name: ack_time
        description: time in unix epoch when ACK button is clicked
      - name: alert_name
        description: name of detection
      - name: alert_time
        description: time  in unix when Devo Detection engine triggers the alert
      - name: assignee
        description: name of person who worked on the alert
      - name: change_assignee
      - name: close_alert
        description: time in unix epoch when an alert was closed
      - name: comments
        description: brief description about alert closure
      - name: convert_incident
        description: Optional field when an alert is converted to an incident
      - name: db_date
        description: identifier for cron job to pick the alerts
      - name: event_time
        description: time  in unix when a specific event occurred
      - name: feature
        description: optional field of alert sent to users
      - name: label
        description: conclusion of a triaged alert
      - name: mitre_tac
        description: Mitre ATT&CK tactic mapping
      - name: mitre_teq
        description: MITRE ATT&CK technique mapping
      - name: sentiment
        description: optional field about feedback of the alert
      - name: gcs_uploaded_at
        description: File modified_at in GCS
        data_tests:
          - not_null
      - name: snowflake_uploaded_at
        description: The datetime when the GCS data was uploaded into Snowflake
        data_tests:
          - not_null
