version: 2

sources:
  - name: google_analytics_4_bigquery
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: google_analytics_4_bigquery
    loaded_at_field: uploaded_at
    loader: Airflow, Google Ananlytics 4
    description: Google Ananlytics 4 Data from Bigquery [Original Issue](https://gitlab.com/gitlab-data/analytics/-/issues/19489)

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: events
        description: "Google Ananlytics 4 events table"
        external:
          location: "@raw.google_analytics_4_bigquery.marketing_ga4_gcs_export/events"
          file_format: "( type = parquet )"
          auto_refresh: false
          partitions:
            - name: date_part
              data_type: date
              expression: to_date(split_part(metadata$filename, '/', -2),'YYYYMMDD')
       
      - name: pseudonymous_users
        description: "Google Ananlytics 4 pseudonymous_users table"
        external:
          location: "@raw.google_analytics_4_bigquery.marketing_ga4_gcs_export/pseudonymous_users"
          file_format: "( type = parquet )"
          auto_refresh: false
          partitions:
            - name: date_part
              data_type: date
              expression: to_date(split_part(metadata$filename, '/', -2),'YYYYMMDD')
