version: 2
models:
  - name: rally_webhook_stitch_optouts_source
    description: Data from Rally application indicating if user is optin or not
    columns:
      - name: email
        data_tests:
          - not_null
      - name: opted_out
        data_tests:
          - not_null
      - name: updated_at
        data_tests:
          - not_null
