version: 2

sources:
  - name: mock_source
    tables:
      - name: mock_source_table
        columns:
          - name: source_column
            meta:
              masking_policy: engineer

models:
    - name: data_type_mock_table
      description: This table with mock data used for development.
      columns:
        - name: the_float
          data_type: number
          meta: 
            masking_policy: analyst_engineering   
        - name: the_varchar
          data_type: string
          meta:
            masking_policy: engineer
        - name: the_int
          meta:
            masking_policy: dbt_analytics
        - name: the_array
          meta:
            masking_policy: dbt_analytics
        - name: the_variant
        - name: the_date
          meta:
            masking_policy: engineer
        - name: the_timestamp
          meta:
            masking_policy: analyst_people
        - name: the_boolean
          meta:
            masking_policy: engineer