version: 2

models:
  - name: category_handbook_engineering_merge_requests
    description: This dbt model (view) just filters category_handbook_merge_requests to only include engineering and support related MRs.
    columns:
    - name: merge_request_created_at
      data_tests:
        - not_null
    - name: merge_request_department_list
      data_tests:
        - not_null
    - name: merge_request_iid
      data_tests: 
        - not_null
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_state
      data_tests:
        - not_null
    - name: merge_request_updated_at
      data_tests:
        - not_null
  - name: category_handbook_merge_requests
    description: This is a dbt model (view) of unique merge requests to the handbook along with their categorization of a specific department/division in engineering.
    columns:
    - name: merge_request_created_at
      data_tests:
        - not_null
    - name: merge_request_department_list
      data_tests:
        - not_null
    - name: merge_request_iid
      data_tests: 
        - not_null
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_state
      data_tests:
        - not_null
    - name: merge_request_updated_at
      data_tests:
        - not_null
  - name: category_handbook_engineering_merge_requests_path_count
    description: This is a dbt model (view) of unique paths per merge requests to the handbook along with their categorization and count for each specific department/division in Engineering.
    columns:
    - name: merge_request_iid
      data_tests:
        - not_null
    - name: merge_request_state
      data_tests:
        - not_null
    - name: merge_request_path
      data_tests:
        - not_null
    - name: path_count_engineering
      data_tests:
        - not_null
    - name: path_count_ux
      data_tests:
        - not_null
    - name: path_count_security
      data_tests:
        - not_null
    - name: path_count_infrastructure
      data_tests:
        - not_null
    - name: path_count_development
      data_tests:
        - not_null
    - name: path_count_quality
      data_tests:
        - not_null
    - name: path_count_support
      data_tests:
        - not_null
    - name: merge_request_created_at
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_updated_at
      data_tests:
        - not_null
  - name: category_handbook_engineering_merge_requests_count
    description: This is a dbt model (view) of unique merge requests to the handbook along with their categorization and count for each specific department/division in Engineering.
    columns:
    - name: merge_request_iid
      data_tests:
        - not_null
    - name: merge_request_state
      data_tests:
        - not_null
    - name: mr_count_engineering
      data_tests:
        - not_null
    - name: mr_count_ux
      data_tests:
        - not_null
    - name: mr_count_security
      data_tests:
        - not_null
    - name: mr_count_infrastructure
      data_tests:
        - not_null
    - name: mr_count_development
      data_tests:
        - not_null
    - name: mr_count_quality
      data_tests:
        - not_null
    - name: mr_count_support
      data_tests:
        - not_null
    - name: merge_request_created_at
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_updated_at
      data_tests:
        - not_null
  - name: category_handbook_business_technology_merge_requests
    description: This dbt model (view) just filters category_handbook_merge_requests to only include Business Technology related MRs.
    columns:
    - name: merge_request_created_at
      data_tests:
        - not_null
    - name: merge_request_department_list
      data_tests:
        - not_null
    - name: merge_request_iid
      data_tests: 
        - not_null
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_state
      data_tests:
        - not_null
    - name: merge_request_updated_at
      data_tests:
        - not_null
  - name: category_handbook_people_group_merge_requests
    description: This dbt model (view) just filters category_handbook_merge_requests to only include People Group related MRs.
    columns:
    - name: merge_request_created_at
      data_tests:
        - not_null
    - name: merge_request_department_list
      data_tests:
        - not_null
    - name: merge_request_iid
      data_tests: 
        - not_null
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_state
      data_tests:
        - not_null
    - name: merge_request_updated_at
      data_tests:
        - not_null
  - name: category_handbook_people_group_merge_requests_path_count
    description: This is a dbt model (view) of unique paths per merge requests to the handbook along with their categorization and count for each specific department/division in People Group.
    columns:
    - name: merge_request_iid
      data_tests:
        - not_null
    - name: merge_request_state
      data_tests:
        - not_null
    - name: merge_request_path
      data_tests:
        - not_null
    - name: path_count_people_group
      data_tests:
        - not_null
    - name: path_count_people_group_engineering
      data_tests:
        - not_null
    - name: merge_request_created_at
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_updated_at
      data_tests:
        - not_null
  - name: category_handbook_people_group_merge_requests_count
    description: This is a dbt model (view) of unique merge requests to the handbook along with their categorization and count for each specific department/division in People Group.
    columns:
    - name: merge_request_iid
      data_tests:
        - not_null
    - name: merge_request_state
      data_tests:
        - not_null
    - name: mr_count_people_group
      data_tests:
        - not_null
    - name: mr_count_people_group_engineering
      data_tests:
        - not_null
    - name: merge_request_created_at
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_updated_at
      data_tests:
        - not_null
