version: 2
 
sources:
 - name: influx_db
   database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
   schema: influx_db
   loaded_at_field: _uploaded_at
   loader: Snowpipe
   description: InfluxDB data [Original Issue](https://gitlab.com/gitlab-data/analytics/-/issues/16279)
 
   quoting:
     database: true
     schema: false
     identifier: false
 
   tables:
     - name: all_fabrication_stats
     - name: all_test_stats
     - name: main_test_stats