version: 2

models:
  - name: create_gitlab_dotcom_smau_events
    description: '{{ doc("create_gitlab_dotcom_smau_events") }}'
    columns:
      - name: user_id
        data_tests:
          - not_null
      - name: event_date
        data_tests:
          - not_null
      - name: event_surrogate_key
        data_tests:
          - not_null

  - name: manage_gitlab_dotcom_smau_events
    description: '{{ doc("manage_gitlab_dotcom_smau_events") }}'
    columns:
      - name: user_id
      - name: event_date
        data_tests:
          - not_null
      - name: event_surrogate_key
        data_tests:
          - not_null
          - unique
