version: 2

sources:
  - name: level_up
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: level_up
    loader: Airflow
    loaded_at_field: uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: assessment_attempts
      - name: clients
      - name: content
      - name: code_redemptions
      - name: course_actions
      - name: course_completions
      - name: course_purchases
      - name: course_views
      - name: coupons
      - name: email_captures
      - name: learning_path_actions
      - name: logins
      - name: meetings
      - name: users
      - name: visits
