version: 2

sources:
  - name: qualtrics_static
    database: '{{ env_var("SNOWFLAKE_STATIC_DATABASE") }}'
    schema: sensitive

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
    - name: qualtrics_post_purchase_survey_answers_from_issue_15225
      freshness: null