version: 2
 
models:
  - name: iterable_campaign_history_source
    description: Base model for campaign_history
    columns:
    - name: iterable_campaign_id
      data_tests:
        - not_null
  - name: iterable_campaign_list_history_source
    description: Base model for campaign_list_history
    columns:
    - name: iterable_campaign_id
      data_tests:
        - not_null
  - name: iterable_campaign_metrics_source
    description: Base model for campaign_metrics
    columns:
    - name: iterable_campaign_id
      data_tests:
        - not_null
  - name: iterable_campaign_suppression_list_history_source
    description: Base model for campaign_suppression_list_history
    columns:
    - name: iterable_campaign_id
      data_tests:
        - not_null
  - name: iterable_channel_source
    description: Base model for channel
    columns:
    - name: iterable_channel_id
      data_tests:
        - not_null
  - name: iterable_email_link_param_history_source
    description: Base model for email_link_parameter
    columns:
    - name: iterable_email_link_param_key
      data_tests:
        - not_null
  - name: iterable_email_template_history_source
    description: Base model for email_template
    columns:
    - name: iterable_email_template_id
      data_tests:
        - not_null
  - name: iterable_event_source
    description: Base model for events
    columns:
    - name: iterable_event_fivetran_id
      data_tests:
        - not_null
  - name: iterable_list_source
    description: Base model for lists
    columns:
    - name: iterable_list_id
      data_tests:
        - not_null
  - name: iterable_list_user_history_source
    description: Base model for list_user interaction
    columns:
    - name: iterable_list_id
      data_tests:
        - not_null
  - name: iterable_message_type_source
    description: Base model for messages
    columns:
    - name: iterable_message_type_id
      data_tests:
        - not_null
  - name: iterable_template_history_source
    description: Base model for templates
    columns:
    - name: iterable_template_id
      data_tests:
        - not_null
  - name: iterable_user_history_source
    description: Base model for user_history
    columns:
    - name: iterable_user_updated_at
      data_tests:
        - not_null
    - name: iterable_user_first_name
      meta:
        sensitive: true
    - name: iterable_user_last_name
      meta:
        sensitive: true
    - name: iterable_user_email
      meta:
        sensitive: true
    - name: iterable_user_phone_number
      meta:
        sensitive: true
  - name: iterable_user_unsubscribed_channel_source
    description: Base model for user_unsubscribed_channel
    columns:
    - name: iterable_user_unsubscribed_channel_id
      data_tests:
        - not_null
  - name: iterable_user_unsubscribed_message_type_source
    description: Base model for user_unsubscribed_message_type
    columns:
    - name: iterable_unsubscribed_message_type_id
      data_tests:
        - not_null