version: 2
 
sources:
 - name: iterable
   database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
   schema: iterable
   loaded_at_field: _fivetran_synced
   loader: fivetran
   description: Iterable data
 
   quoting:
     database: true
     schema: false
     identifier: false
 
   tables:
     - name: user_history
     - name: user_unsubscribed_channel
     - name: user_unsubscribed_message_type
     - name: list_user_history
     - name: list
     - name: campaign_metrics
     - name: email_link_param_history
     - name: campaign_history
     - name: email_template_history
     - name: template_history
     - name: campaign_list_history
     - name: event
     - name: channel
     - name: campaign_suppression_list_history
     - name: message_type