version: 2
models:
  - name: elastic_billing_resources_source
    description: Reports on a monthly basis the detailed ElasticSearch billing data,
      per resource.
    columns:
      - name: extraction_start_date
        description: First day of the billing period. Each billing period is a month.
      - name: extraction_end_date
        description: Last day of the billing period. Last day of every month.
      - name: resource_start_date
        description: When the usage of the resource started
      - name: resource_end_date
        description: When the usage of the resource ended
      - name: hours
        description: Amount of hours during the interval
      - name: instance_count
        description: Amount of instances
      - name: kind
        description: Kind of the instances
      - name: cost
        description: Cost of the charge in ECU
      - name: name
        description: Name of the resources
      - name: price_per_hour
        description: Cost per hour for the group of instances
      - name: sku
        description: Name of the SKU
      - name: _uploaded_at
        description: When the source model was updated

  - name: elastic_billing_data_transfer_source
    description: ""
    columns:
      - name: extraction_start_date
        description: First day of the billing period. Each billing period is a month.
      - name: extraction_end_date
        description: Last day of the billing period. Each billing period is a month.
      - name: charge_type
        description: Type of the charge
      - name: cost
        description: Cost for the charge in ECU
      - name: resource_name
        description: Name of the resource used
      - name: resource_quantity_value
        description: Usage for the charge (raw value)
      - name: formated_quantity_value
        description: Usage for the charge (formatted value)
      - name: rate_value
        description: Rate for the charge
      - name: formated_rate_value
        description: Rate for the charge
      - name: sku
        description: SKU name for the charge
      - name: type
        description: Charge type
      - name: _uploaded_at
        description: When the source model was updated

  - name: elastic_billing_data_transfer_by_deployment_source
    description: Reports on a cummulative daily cost basis the detailed ElasticSearch billing data, per deployment
      per resource, per month for data transfer 
    columns:
      - name: deployment_id
        description: The id assigned for each deployment in Elastic
        data_tests:
          - not_null
      - name: extraction_start_date
        description: First day of the billing period. Each billing period is a month
        data_tests:
          - not_null
      - name: extraction_end_date
        description: Last day of the billing period. Last day of every month
        data_tests:
          - not_null
      - name: charge_type
        description: Type of the charge
      - name: cost
        description: Cost for the charge in ECU
      - name: resource_name
        description: Name of the resource used
      - name: resource_quantity_value
        description: Usage for the charge (raw value)
      - name: formated_quantity_value
        description: Usage for the charge (formatted value)
      - name: rate_value
        description: Rate for the charge
      - name: formated_rate_value
        description: Rate for the charge
      - name: sku
        description: SKU name for the charge
      - name: type
        description: Charge type
      - name: _uploaded_at
        description: When the source model was updated

  - name: elastic_billing_resources_by_deployment_source
    description: Reports on a cummulative daily cost basis the detailed ElasticSearch billing data, per deployment
      per resource, per month
    columns:
      - name: deployment_id
        description: The id assigned for each deployment in Elastic
        data_tests:
          - not_null
      - name: extraction_start_date
        description: First day of the billing period. Each billing period is a month
        data_tests:
          - not_null
      - name: extraction_end_date
        description: Last day of the billing period. Each billing period is a month
        data_tests:
          - not_null
      - name: resource_start_date
        description: When the usage of the resource started
      - name: resource_end_date
        description: When the usage of the resource ended
      - name: hours
        description: Amount of hours during the interval
      - name: instance_count
        description: Amount of instances
      - name: kind
        description: Kind of the instances
      - name: cost
        description: Cost of the charge in ECU
      - name: resource_name
        description: Name of the resources
      - name: price_per_hour
        description: Cost per hour for the group of instances
      - name: sku
        description: Name of the SKU
      - name: _uploaded_at
        description: When the source model was updated