version: 2

sources:
  - name: elastic_billing
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: elasticsearch_billing
    loader: Airflow

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: itemized_costs
      - name: itemized_costs_by_deployment

