version: 2

models:
  - name: rpt_engineering_handbook_update_frequency_monthly
    description: This is a dbt model (view) of total count of Handbook MR file changes for each specific department/division in Engineering.
    columns:
    - name: month_merged_at
      data_tests:
        - not_null
    - name: mr_count_engineering
      data_tests:
        - not_null
    - name: mr_count_ux
      data_tests:
        - not_null
    - name: mr_count_security
      data_tests:
        - not_null
    - name: mr_count_infrastructure
      data_tests:
        - not_null
    - name: mr_count_development
      data_tests:
        - not_null
    - name: mr_count_quality
      data_tests:
        - not_null
    - name: mr_count_support
      data_tests:
        - not_null
  - name: rpt_people_group_handbook_update_frequency_monthly
    description: This is a dbt model (view) of total count of Handbook MR file changes for each specific department/division in the People Group.
    columns:
    - name: month_merged_at
      data_tests:
        - not_null
    - name: mr_count_people_group
      data_tests:
        - not_null
    - name: mr_count_people_group_engineering
      data_tests:
        - not_null
