version: 2
models:
  - name: level_up_users_source
    description: Returns all Users
    columns:
      - name: allocated_learning_paths
      - name: allocated_licenses
      - name: asset
      - name: balance
      - name: client_id
      - name: country
      - name: created_at
      - name: custom_fields
      - name: is_disabled
      - name: username
      - name: external_customer_id
      - name: first_name
      - name: user_id
        data_tests:
          - not_null
          - unique
      - name: language
      - name: last_active_at
      - name: last_name
      - name: learner_user_id
      - name: manager_user_id
      - name: purchased_bundles
      - name: purchased_courses
      - name: ref1_user_type
      - name: ref10_user_dept
      - name: ref2_user_job
      - name: ref4_user_company
      - name: ref5
      - name: ref6_user_role_type
      - name: ref7_user_continent
      - name: ref8_user_country
      - name: ref9_user_sub_dept
      - name: role_key
      - name: sf_account_id
      - name: sf_contact_id
      - name: shipping_name
      - name: state
      - name: stripe_customer_id
      - name: waitlisted_courses
      - name: zip_code
      - name: uploaded_at
        data_tests:
          - not_null
