version: 2

models:
  - name: category_marketing_site_merge_requests
    description: This is a dbt model (view) of unique merge requests to the marketing site along with their categorization of a specific department/division.
    columns:
    - name: merge_request_created_at
      data_tests:
        - not_null
    - name: merge_request_department_list
      data_tests:
        - not_null
    - name: merge_request_iid
      data_tests: 
        - not_null
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_state
      data_tests:
        - not_null
    - name: merge_request_updated_at
      data_tests:
        - not_null
  - name: category_marketing_security_merge_requests
    description: This dbt model (view) just filters category_marketing_site_merge_requests to only include security related MRs.
    columns:
    - name: merge_request_created_at
      data_tests:
        - not_null
    - name: merge_request_department_list
      data_tests:
        - not_null
    - name: merge_request_iid
      data_tests: 
        - not_null
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_state
      data_tests:
        - not_null
    - name: merge_request_updated_at
      data_tests:
        - not_null
  - name: category_marketing_security_merge_requests_path_count
    description: This is a dbt model (view) of unique paths per merge requests to the marketing site along with their categorization and count for each specific department/division.
    columns:
    - name: merge_request_iid
      data_tests:
        - not_null
    - name: merge_request_state
      data_tests:
        - not_null
    - name: merge_request_path
      data_tests:
        - not_null
    - name: path_count_security
      data_tests:
        - not_null
    - name: merge_request_created_at
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_updated_at
      data_tests:
        - not_null
  - name: category_marketing_security_merge_requests_count
    description: This is a dbt model (view) of unique merge requests to the marketing site along with their categorization and count for each specific department/division.
    columns:
    - name: merge_request_iid
      data_tests:
        - not_null
    - name: merge_request_state
      data_tests:
        - not_null
    - name: mr_count_security
      data_tests:
        - not_null
    - name: merge_request_created_at
    - name: merge_request_last_edited_at
    - name: merge_request_merged_at
    - name: merge_request_updated_at
      data_tests:
        - not_null


