version: 2

sources:
  - name: linkedin_ads
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: linkedin_ads
    loaded_at_field: _fivetran_synced
    loader: fivetran
    description: Linkedin Ads data [Original Issue](https://gitlab.com/gitlab-data/analytics/-/issues/15160)

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: campaign_history
      - name: creative_history
      - name: ad_analytics_by_creative
