version: 2

models:
  - name: zuora_order_source
    description: ' {{ doc("zuora_order_source") }}'
    columns:
      - name: order_id
        tags: ["tdf", "zuora"]
        data_tests:
          - not_null
          - unique
  - name: zuora_order_action_source
    description: ' {{ doc("zuora_order_action_source") }}'
    columns:
      - name: order_action_id
        tags: ["tdf", "zuora"]
        data_tests:
          - not_null
          - unique