version: 2

models:
  - name: commonroom_activities_source
    description: '{{ doc("commonroom_activities_source") }}'
    columns:
      - name: primary_key
        description: '{{ doc("commonroom_primary_key") }}'
        data_tests:
            - unique
            - not_null
      - name: activity_timestamp
        data_tests:
          - not_null
      - name: activity_type
        data_tests:
          - not_null
      - name: first_activity_date
      - name: full_name
        meta:
          sensitive: true
        data_tests:
          - not_null
      - name: member_id
      - name: profiles
        meta:
          sensitive: true
      - name: service_name
        data_tests:
          - not_null
      - name: _uploaded_at
        description: '{{ doc("_uploaded_at") }}'
      - name: _file_name
        description: '{{ doc("_file_name") }}'
  - name: commonroom_community_members_source
    description: '{{ doc("commonroom_community_members_source") }}'
    columns:
      - name: primary_key
        data_tests:
            - unique
            - not_null
      - name: first_activity_date
      - name: first_activity_source
      - name: full_name
        data_tests:
          - not_null
        meta:
          sensitive: true
      - name: impact_points_all_time
      - name: last_activity_date
      - name: location
        meta:
          sensitive: true
      - name: member_ids
        description: '{{ doc("commonroom_member_ids") }}'
      - name: primary_email
        meta:
          sensitive: true
      - name: profiles
        meta:
          sensitive: true
        data_tests:
          - not_null
      - name: segment_names
      - name: tags
      - name: job_title
      - name: last_organization
      - name: organization_name
      - name: organization_domain
      - name: _uploaded_at
        description: '{{ doc("_uploaded_at") }}'
      - name: _file_name
        description: '{{ doc("_file_name") }}'
  - name: commonroom_organizations_source
    description: '{{ doc("commonroom_organizations_source") }}'
    columns:
      - name: primary_key
        data_tests:
            - unique
            - not_null
      - name: approx_revenue_max
      - name: approx_revenue_min
      - name: domain
        data_tests:
          - not_null
      - name: employee_count
        data_tests:
          - not_null
      - name: first_seen_date
      - name: first_seen_source
      - name: last_seen_date
      - name: location
        meta:
          sensitive: true
      - name: member_count
      - name: organization_name
        meta:
          sensitive: true
        data_tests:
          - not_null
      - name: _uploaded_at
        description: '{{ doc("_uploaded_at") }}'
      - name: _file_name
        description: '{{ doc("_file_name") }}'