version: 2

sources:
  - name: commonroom
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: commonroom
    loader: Snowflake task
    loaded_at_field: _uploaded_at
    description: Common Room data [Original Issue](https://gitlab.com/gitlab-data/analytics/-/issues/19690)

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
    - name: activities
      description: '{{ doc("commonroom_activities_source") }}'
      columns:
        - name: activity_timestamp
        - name: activity_type
        - name: first_activity_date
        - name: full_name
        - name: member_id
        - name: profiles
        - name: service_name
        - name: _uploaded_at
        - name: _file_name
    - name: community_members
      description: '{{ doc("commonroom_community_members_source") }}'
      columns:
        - name: first_activity_date
        - name: first_activity_source
        - name: full_name
        - name: impact_points_all_time
        - name: last_activity_date
        - name: location
        - name: member_ids
          description: '{{ doc("commonroom_member_ids") }}'
        - name: primary_email
        - name: profiles
        - name: segment_names
        - name: tags
        - name: job_title
        - name: last_organization
        - name: organization_name
        - name: organization_domain
        - name: _uploaded_at
        - name: _file_name
    - name: organizations
      description: '{{ doc("commonroom_organizations_source") }}'
      columns:
        - name: approx_revenue_max
        - name: approx_revenue_min
        - name: domain
        - name: employee_count
        - name: first_seen_date
        - name: first_seen_source
        - name: last_seen_date
        - name: location
        - name: member_count
        - name: organization_name
        - name: _uploaded_at
        - name: _file_name