version: 2

models:
  - name: sensitive_queries_tags
    description: '{{ doc("sensitive_queries_tags_doc") }}'
    columns:
      - name: classification_type
        description: '{{ doc("classification_type_doc") }}'
      - name: tag_name
        description: '{{ doc("tag_name_doc") }}'
      - name: tag_value
        description: '{{ doc("tag_value_doc") }}'
      - name: accessed_database
      - name: accessed_schema
      - name: accessed_table
      - name: accessed_column
  - name: sensitive_queries_base
    description: '{{ doc("sensitive_queries_base_doc") }}'
    columns:
      - name: classification_type
        description: '{{ doc("classification_type_doc") }}'
      - name: query_id
        description: '{{ doc("query_id_doc") }}'
      - name: user_name
      - name: accessed_database
      - name: accessed_schema
      - name: accessed_table
      - name: query_text
      - name: executed_from_database_name
      - name: executed_from_schema_name
      - name: query_type
      - name: role_name
      - name: start_time
        description: '{{ doc("start_time_doc") }}'
      - name: end_time
        description: '{{ doc("end_time_doc") }}'
      - name: accessed_column
      - name: tag_name
        description: '{{ doc("tag_name_doc") }}'
      - name: tag_value
        description: '{{ doc("tag_value_doc") }}'
  - name: sensitive_queries_source
    description: '{{ doc("sensitive_queries_source_doc") }}'
    columns:
      - name: classification_type
        description: '{{ doc("classification_type_doc") }}'
      - name: query_id
        description: '{{ doc("query_id_doc") }}'
      - name: user_name
      - name: accessed_database
      - name: accessed_schema
      - name: accessed_table
      - name: query_text
      - name: executed_from_database_name
      - name: executed_from_schema_name
      - name: query_type
      - name: role_name
      - name: start_time
        description: '{{ doc("start_time_doc") }}'
      - name: end_time
        description: '{{ doc("end_time_doc") }}'
      - name: _uploaded_at
        description: '{{ doc("_uploaded_at_doc") }}'
  - name: sensitive_queries_details
    description: '{{ doc("sensitive_queries_details_doc") }}'
    columns:
      - name: classification_type
        description: '{{ doc("classification_type_doc") }}'
      - name: query_id
        description: '{{ doc("query_id_doc") }}'
      - name: accessed_column
      - name: tag_name
        description: '{{ doc("tag_name_doc") }}'
      - name: tag_value
        description: '{{ doc("tag_value_doc") }}'
      - name: start_time
        description: '{{ doc("start_time_doc") }}'
      - name: _uploaded_at
        description: '{{ doc("_uploaded_at_doc") }}'