version: 2

models:
    - name: key_assets
      description: "Key assets list as extracted from Monte Carlo."
    - name: monitors
      description: "Monte Carlo monitors."
    - name: cleanup_suggestions
      description: "Monte Carlo clanup suggestions."
    - name: dashboard_analytics
      description: "Monte Carlo dashboard analytics, such as number of issues, types of issues etc."
    - name: field_cleanup_suggestions
      description: "Monte Carlo field cleanup suggestions, based on how often these columns are used in queries."
    - name: incident_history
      description: "Monte Carlo list of incidents."
    - name: monitor_issues_and_solutions
      description: "Monte Carlo list of issues and solutions."
    - name: monitor_recom_field_health
      description: "Monte Carlo exported field health information."
    - name: events
      description: "Monte Carlo exported list of events."